import { DM_Sans } from "next/font/google";
import "./styles/style.css";
import "./styles/res.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const DMSans = DM_Sans({
  variable: "--main_font",
  subsets: ["latin"],
});

export const metadata = {
  title: "Gwebpro Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${DMSans.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
